### PR TITLE
skills: Add Kotlin

### PR DESCRIPTION
**Pull request by Dhina17**
Will update links once you provide from your side.

### CODE REVIEW

**Review by danielcranney — APPROVED** [review]
Thank you so much for your contribution. I'll merge this into the main branch now.

**Comment by Dhina17** [comment]
@danielcranney Thank you for your merge. But I think links are meant to be updated from you repo like all other svg files.

**Comment by Dhina17** [comment]
Nvm, you did it.

**Comment by danielcranney** [comment]
No problem at all. I appreciate your addition!

**Pull request merged**
